version: "3.8"
services:
  db:
    volumes:
      - postgres:/data/postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat-app
    ports:
      - "5433:5433"
    container_name: postgres

  backend:
    build:
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat-app
      - POSTGRES_URI=postgres://postgres:postgres@db:5432/chat-app
      - CORS_ORIGIN=http://localhost:3000
      - PORT=5000
      - JWT_SECRET='nåtsomärhemligt'

  frontend:
    build:
      dockerfile: Dockerfile.frontend
      args:
        API_URL: http://localhost:5000
    ports:
      - "3000:3000"

volumes:
  postgres:
